### ISSUE TITLE
Bad Authentication data

### ISSUE THREAD

**Issue by ACChe** [haarts/golang_news#2]
Error posting tweet: Get https://api.twitter.com/1.1/statuses/update.json returned status 400, {"errors":[{"message":"Bad Authentication data","code":215}]}

what the problem is?

**Comment by haarts** [comment]
I had NO idea this issue was here. I'm sorry! Uhmmm, is this still relevant after 3 years?

**Comment by ACChe** [comment]
Had fixed! THX
